# =========================================================
# V2Shop - Telegram VPN Shop Bot Core (Python)
# Auto-generated by V2Shop Management Console
# =========================================================

import os
import logging
import asyncio
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    CallbackQueryHandler,
    ContextTypes,
    MessageHandler,
    filters
)

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

BOT_TOKEN = os.getenv("BOT_TOKEN", "7192834012:AAH9f2Xk8qL0mW1n2P3o4Q5r6S7t8U9v0W")
SUPPORT_USER = os.getenv("SUPPORT_USERNAME", "V2Shop_Admin_Support")
CARD_NUMBER = os.getenv("CARD_NUMBER", "6037 9975 1234 5678")
CARD_HOLDER = os.getenv("CARD_HOLDER", "محمد امینی")

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    welcome_text = (
        f"👋 سلام {user.first_name} عزیز!\n\n"
        f"به ربات فروشگاه وی‌پی‌ان V2Shop خوش آمدید!\n\n"
        f"⚡ برای خرید اشتراک یا تمدید، یکی از گزینه‌های زیر را انتخاب کنید:"
    )
    
    keyboard = [
        [
            InlineKeyboardButton("🛍️ خرید اشتراک جدید", callback_data="buy_plans"),
            InlineKeyboardButton("👤 حساب کاربری من", callback_data="my_account")
        ],
        [
            InlineKeyboardButton("🔗 دریافت لینک ساب‌اسکریپشن", callback_data="get_sub"),
            InlineKeyboardButton("🌐 لیست سرورها و نودها", callback_data="server_list")
        ],
        [
            InlineKeyboardButton("💳 شارژ کیف پول", callback_data="charge_wallet"),
            InlineKeyboardButton("🎁 کد تخفیف / هدیه", callback_data="discount_code")
        ],
        [
            InlineKeyboardButton("💬 پشتیبانی تلگرام", url=f"https://t.me/{SUPPORT_USER}"),
            InlineKeyboardButton("📚 راهنمای اتصال", callback_data="tutorial")
        ]
    ]
    
    reply_markup = InlineKeyboardMarkup(keyboard)
    if update.callback_query:
        await update.callback_query.answer()
        await update.callback_query.edit_message_text(welcome_text, reply_markup=reply_markup)
    else:
        await update.message.reply_text(welcome_text, reply_markup=reply_markup)

async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    
    data = query.data
    if data == "buy_plans":
        text = "📦 **انتخاب پلن اشتراک:**\n\n1️⃣ پلن اقتصادی ۳۰ گیگ (۱ ماهه) - ۱۱۰,۰۰۰ تومان\n2️⃣ پلن حرفه‌ای ۶۰ گیگ (۱ ماهه) - ۱۸۰,۰۰۰ تومان ⭐\n3️⃣ پلن طلایی ۱۵۰ گیگ (۳ ماهه) - ۴۲۰,۰۰۰ تومان"
        keyboard = [
            [InlineKeyboardButton("خرید پلن ۳۰ گیگ (۱۱۰ هزار تومان)", callback_data="pay_plan_1")],
            [InlineKeyboardButton("خرید پلن ۶۰ گیگ (۱۸۰ هزار تومان) ⭐", callback_data="pay_plan_2")],
            [InlineKeyboardButton("خرید پلن ۱۵۰ گیگ (۴۲۰ هزار تومان)", callback_data="pay_plan_3")],
            [InlineKeyboardButton("🔙 بازگشت به منوی اصلی", callback_data="main_menu")]
        ]
        await query.edit_message_text(text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode="Markdown")
        
    elif data.startswith("pay_plan_"):
        text = f"💳 **روش پرداخت:**\n\nجهت واریز کارت به کارت:\nشماره کارت: `{CARD_NUMBER}`\nبنام: {CARD_HOLDER}\n\nپس از واریز، تصویر فیش واریزی را در همین چت ارسال نمایید."
        keyboard = [[InlineKeyboardButton("🔙 بازگشت", callback_data="buy_plans")]]
        await query.edit_message_text(text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode="Markdown")

    elif data == "main_menu":
        await start(update, context)

def main():
    print("🚀 Starting V2Shop Telegram Bot...")
    app = ApplicationBuilder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.run_polling()

if __name__ == '__main__':
    main()
